name: dbt_audit
version: 0.0.3
config-version: 2
require-dbt-version: [">=1.3.0", "<1.9.0"]
profile: dbt_audit

on-run-start:
  - "{{ dbt_audit.on_run_start() }}"
on-run-end:
  - "{{ dbt_audit.on_run_end() }}"
