name: dbt_audit
version: 0.1.12
config-version: 2
require-dbt-version: [">=1.3.0", "<1.10.0"]
profile: dbt_audit

on-run-start:
  - "{{ dbt_audit.on_run_start() if dbt_audit.is_run_command() }}"
on-run-end:
  - "{{ dbt_audit.on_run_end() if dbt_audit.is_run_command() }}"
